version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    networks:
      - traefik-private
    deploy:  
      labels:
        - traefik.enable=true
        - traefik.http.services.pihole.loadbalancer.server.port=80 
        - traefik.http.routers.pihole.entrypoints=websecure
        - traefik.http.routers.pihole.tls=true
        - traefik.http.routers.pihole.tls.certresolver=le
        - traefik.http.routers.pihole.rule=Host(`pihole.icestation.is`)
        - traefik.http.routers.pihole.middlewares=pihole
        - traefik.http.middlewares.pihole.addPrefix.prefix=/admin
        - traefik.docker.network=traefik-private
  
    volumes:
      - /swarm/pihole/etc/pihole/:/etc/pihole/
      - /swarm/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 8.8.8.8
      - 1.1.1.1
networks:
    traefik-private:
        external: true
