version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    networks:
      - traefik-private
    environment:
      TZ: 'America/Los Angeles'
    deploy:  
      labels:
        - traefik.enable=true
        - traefik.http.routers.pihole.rule=Host('pihole.icestation.is')
        - treafik.http.routers.pihole.tls=true
        - traefik.docker.network=traefik-private
        - traefik.port=80
    volumes:
      - /swarm/pihole/etc/pihole/:/etc/pihole/
      - /swarm/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 8.8.8.8
      - 1.1.1.1
networks:
    traefik-private:
        external: true

