version: '3.8'
services:
  grafana:
    image: grafana/grafana:master
    user: '1000'
    networks:
      - traefik-private
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=le
        - traefik.http.routers.grafana.rule=Host(`grafana.icestation.is`)
        - traefik.docker.network=traefik-private
    volumes:
      - /swarm/grafana/var/lib/grafana:/var/lib/grafana
      - /swarm/grafana/etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /swarm/grafana/etc/grafana/provisioning/:/etc/grafana/provisioning/
  prometheus:
    image: prom/prometheus:main
    user: "1000:1000"
    ports:
      - 9090:9090
    volumes:
      - /swarm/prometheus/etc/prometheus/:/etc/prometheus/
      - /swarm/prometheus/data:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - "--web.enable-lifecycle"
  graphite:
    image: "graphiteapp/graphite-statsd:latest"
    volumes:
       - /swarm/graphite/opt/graphite/conf:/opt/graphite/conf
       - /swarm/graphite/opt/graphite/storage:/opt/graphite/storage
       - /swarm/graphite/graphite-api.yaml:/opt/graphite/graphite-api.yaml
    environment:
       - "CARBON_AGGREGATOR_DISABLED=1"
       - "REDIS_DISABLED=1"
       - "STATSD_DISABLED=1"
  influxdb:
    image: influxdb:1.8.10 
    ports:
      - 8082:8082
      - 8086:8086
      - 8089:8089
    volumes:
      - /swarm/influxdb/etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /swarm/influxdb/var/lib/influxdb/data:/var/lib/influxdb/data
networks:
    traefik-private:
        external: true

