
# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  auth_providers:
     type: homeassistant

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 10.0.1.62

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
